use_frameworks!

target 'CRAnimation_Example' do
  pod 'CRAnimation',        :path => '../'
  pod 'FLAnimatedImage',    '~> 1.0'
  pod 'YLGIFImage'
  pod 'SDWebImage',         '~> 3.8.2'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'JHUD'
  pod 'WCLShineButton'

  target 'CRAnimation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
