use_frameworks!

target 'CRAnimation_Example' do
  pod 'CRAnimation',        :path => '../'
  pod 'FLAnimatedImage',    '~> 1.0'
  pod 'YLGIFImage'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'JHUD'
  pod 'WCLShineButton'
  pod 'RxWebViewController'
  pod 'FoldingTabBar'
  pod 'Pull-to-Refresh.Rentals-IOS', '~> 1.0'
  pod 'BearSkill', :git => 'https://github.com/BearRan/BearSkill.git', :commit => 'c33d282'
  pod 'RQShineLabel'
  pod 'NVActivityIndicatorView'
  pod 'LTMorphingLabel'
  pod 'CRRefresh'

  target 'CRAnimation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
